# Generated by Django 5.2.15 on 2026-06-06 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero_participantes', models.PositiveIntegerField()),
                ('aporte_participante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primer_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('segundo_premio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tercer_premio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sorteada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Seleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=2)),
                ('fase', models.IntegerField(choices=[(1, 'Grupos'), (2, 'Dieciseisavos'), (3, 'Octavos'), (4, 'Cuartos'), (5, 'Semifinales'), (6, 'Final')], default=1)),
                ('eliminado', models.BooleanField(default=False)),
                ('es_tercero', models.BooleanField(default=False)),
                ('es_subcampeon', models.BooleanField(default=False)),
                ('es_campeon', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quinielas.quiniela')),
                ('selecciones', models.ManyToManyField(blank=True, to='quinielas.seleccion')),
            ],
        ),
    ]
