# Generated by Django 5.2.15 on 2026-06-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiniela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('numero_participantes', models.PositiveIntegerField()),
                ('aporte_participante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primer_premio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('segundo_premio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tercer_premio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
