# Generated by Django 5.2.15 on 2026-06-04 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='quiniela',
            name='sorteada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_union', models.DateTimeField(auto_now_add=True)),
                ('equipos', models.ManyToManyField(blank=True, to='quinielas.equipo')),
                ('quiniela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='quinielas.quiniela')),
            ],
        ),
    ]
