# Generated by Django 5.2.15 on 2026-06-08 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiniela',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
