# Generated by Django 5.2.15 on 2026-06-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0002_quiniela_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='identificador',
            field=models.CharField(default='', max_length=100),
        ),
    ]
