# Generated by Django 5.2.15 on 2026-06-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0002_equipo_quiniela_sorteada_participante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipo',
            new_name='Seleccion',
        ),
        migrations.RenameField(
            model_name='participante',
            old_name='equipos',
            new_name='selecciones',
        ),
    ]
