# Generated by Django 5.2.15 on 2026-06-04 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0003_rename_equipo_seleccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='seleccion',
            name='grupo',
        ),
        migrations.AddField(
            model_name='seleccion',
            name='bombo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quinielas.bombo'),
        ),
    ]
