# Generated by Django 5.2.15 on 2026-06-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0003_participante_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='codigo',
            field=models.CharField(max_length=6),
        ),
    ]
