# Generated by Django 5.2.15 on 2026-06-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0004_bombo_remove_seleccion_grupo_seleccion_bombo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleccion',
            name='bombo',
        ),
        migrations.DeleteModel(
            name='Bombo',
        ),
    ]
