# Generated by Django 5.2.15 on 2026-06-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0005_remove_seleccion_bombo_delete_bombo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='es_campeon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='es_subcampeon',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='es_tercero',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seleccion',
            name='fase',
            field=models.CharField(choices=[('grupos', 'Grupos'), ('octavos', 'Octavos'), ('cuartos', 'Cuartos'), ('semis', 'Semifinales'), ('final', 'Final')], default='grupos', max_length=20),
        ),
    ]
