# Generated by Django 5.2.15 on 2026-06-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0006_seleccion_eliminado_seleccion_es_campeon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='fase',
            field=models.CharField(choices=[('G', 'Grupos'), ('D', 'Dieciseisavos'), ('O', 'Octavos'), ('C', 'Cuartos'), ('S', 'Semifinales'), ('F', 'Final')], default='D', max_length=20),
        ),
    ]
