# Generated by Django 5.2.15 on 2026-06-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0007_alter_seleccion_fase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seleccion',
            name='fase',
        ),
    ]
