# Generated by Django 5.2.15 on 2026-06-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0010_remove_seleccion_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='fase',
            field=models.IntegerField(choices=[(1, 'Grupos'), (2, 'Dieciseisavos'), (3, 'Octavos'), (4, 'Cuartos'), (5, 'Semifinales'), (6, 'Final')], default=1),
        ),
    ]
