# Generated by Django 5.2.15 on 2026-06-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0011_seleccion_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='seleccion',
            name='code',
            field=models.CharField(default='', max_length=2),
        ),
    ]
