# Generated by Django 5.2.15 on 2026-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quinielas', '0012_seleccion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccion',
            name='code',
            field=models.CharField(max_length=2),
        ),
    ]
